application: ladypenh
version: 3
runtime: python
api_version: 1

default_expiration: '3650d'

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  secure: optional
  login: admin

- url: /media
  static_dir: _generated_media
  secure: optional

- url: /favicon.ico
  static_files: ladypenh/media/default/favicon.ico
  upload: ladypenh/media/default/favicon.ico

- url: /.*
  script: common/appenginepatch/main.py
  secure: optional

builtins:
- remote_api: on
